diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
user.name=Douglas Mendes
user.email=capudougmor@gmail.com
filesystem.Oracle Corporation|12.0.1|40834876.timestampresolution=46878 microseconds
filesystem.Oracle Corporation|12.0.1|40834876.minracythreshold=0 nanoseconds
filesystem.Oracle Corporation|12.0.1|1882628895.timestampresolution=15626 microseconds
filesystem.Oracle Corporation|12.0.1|1882628895.minracythreshold=0 nanoseconds
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/capudougmor/ReservaHotel
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
